''' NUMPY - Numerical Python
NumPy is a Python Library
NumPy is used for working with arrays. '''

In [2]:
#plp install NumPy

In [3]:
#PYPL website name"

In [5]:
import numpy

In [11]:
a = numpy.array(1)
print(a)

1


In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
import numpy as np
print(np.__version__)

1.26.4


In [15]:
#pipshow numpy

#Dimension Array

0 - dimension array
1 - dimension array
2 - dimension array
3 - dimension array

 

In [18]:
#0 dimension array

import numpy as np
a=np.array(0)
print(a.ndim)

0


In [29]:
#1 dimension array

import numpy as np
n=np.array([1,2,3])
print(n.ndim)

1


In [24]:
#2 dimension array
import numpy as np
a=np.array([[1,2,3],[1,2,3]])
print(a.ndim)

2


In [26]:
#2 dimension array
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a.ndim)

2


In [28]:
#3 dimension array
import numpy as np
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(a.ndim)

3


In [34]:
l=[[1,3],[5,9,89],[3,4,5]]
l[1][1]

9

In [4]:
import numpy as np 
a=np.array([[1,2,3,4],[5,6,7,8]])
a[1,1:3]

array([6, 7])

In [8]:
import numpy as np 
a=np.array([[1,2,3,4],[5,6,7,8]])
a[1,1:4]

array([6, 7, 8])

In [9]:
#datatypes

#i - integer
#b  - boolean
#u - unsigned integer
#f - float
#c - complex float
#s - String

In [10]:
#dtype
#astype

In [12]:
#copy and View
# copy: duplicate the copy and the value is affected only in duplicate one
#view: duplicate the copy and the value is affected both duplicate and source one

In [29]:
l1=[1,2,3]
l2=[4,5,6]
l=[]
for i in l1:
    for j in l2:
        l3=i+j
    l.append(l3)   
print(l)

[7, 8, 9]


In [34]:
l1=[1,2,3]
l2=[4,5,6]
l=[]
for i in range(len(l1)):
    print(l1[i],l2[i])
    l.append(l1[i]+l2[i])
l

1 4
2 5
3 6


[5, 7, 9]

In [42]:
import numpy as np

a=np.array([[1,2,3],[4,6,3]])
b=np.array([[3,6,4],[1,2,5]])
addition = a+b
subtraction = a-b
division = a/b
multiplication = a*b

print("addition",addition)
print("sub",subtraction)
print("divide",division)
print("multiplication",multiplication)
print("modulus",a%b)
print("floor division",a//b)

addition [[4 8 7]
 [5 8 8]]
sub [[-2 -4 -1]
 [ 3  4 -2]]
divide [[0.33333333 0.33333333 0.75      ]
 [4.         3.         0.6       ]]
multiplication [[ 3 12 12]
 [ 4 12 15]]
modulus [[1 2 3]
 [0 0 3]]
floor division [[0 0 0]
 [4 3 0]]


array reshape

In [2]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_array=x.reshape(4,3)
print(reshape_array)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
import numpy as np
x=np.array([1,3,4,5,6,7,8,10,11,13])
reshape_array=x.reshape(5,2)
print(reshape_array)

[[ 1  3]
 [ 4  5]
 [ 6  7]
 [ 8 10]
 [11 13]]


In [5]:
import numpy as np
x=np.array([1,3,4,5,6,7,8,10,11,13])
reshape_array=x.reshape(2,5)
print(reshape_array)

[[ 1  3  4  5  6]
 [ 7  8 10 11 13]]


In [10]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_array=x.reshape(3,2,2)
print(reshape_array)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [12]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshape_array=x.reshape(2,6,1)
print(reshape_array)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]]


In [14]:
#using loops
#nditer
#enumerate
#concatenate
#split
